insert into restaurants (name, elo) values('Amaya Express', '1000');
insert into restaurants (name, elo) values('A&W', '1000');
insert into restaurants (name, elo) values('Baton Rouge', '1000');
insert into restaurants (name, elo) values('Booster Juice', '1000');
insert into restaurants (name, elo) values('Boston Pizza', '1000');
insert into restaurants (name, elo) values('Burger King', '1000');
insert into restaurants (name, elo) values('Chipotle Mexican Grill', '1000');
insert into restaurants (name, elo) values('Cinnabon', '1000');
insert into restaurants (name, elo) values('Coffee Time', '1000');
insert into restaurants (name, elo) values('Country Style', '1000');
insert into restaurants (name, elo) values('Cows Ice Cream', '1000');
insert into restaurants (name, elo) values('Dairy Queen', '1000');
insert into restaurants (name, elo) values('East Side Mario''s', '1000');
insert into restaurants (name, elo) values('Edo Japan', '1000');
insert into restaurants (name, elo) values('Extreme Pita', '1000');
insert into restaurants (name, elo) values('Five Guys', '1000');
insert into restaurants (name, elo) values('Freshii', '1000');
insert into restaurants (name, elo) values('Goji''s', '1000');
insert into restaurants (name, elo) values('Harvey''s', '1000');
insert into restaurants (name, elo) values('Hero Certified Burgers', '1000');
insert into restaurants (name, elo) values('Jack Astor''s Bar and Grill', '1000');
insert into restaurants (name, elo) values('Jimmy the Greek', '1000');
insert into restaurants (name, elo) values('JOEY', '1000');
insert into restaurants (name, elo) values('Kelsey''s Neighbourhood Bar & Grill', '1000');
insert into restaurants (name, elo) values('KFC', '1000');
insert into restaurants (name, elo) values('Krispy Kreme', '1000');
insert into restaurants (name, elo) values('Manchu Wok', '1000');
insert into restaurants (name, elo) values('Mandarin Restaurant', '1000');
insert into restaurants (name, elo) values('McDonald''s', '1000');
insert into restaurants (name, elo) values('Milestones Grill and Bar', '1000');
insert into restaurants (name, elo) values('Montana''s Cookhouse', '1000');
insert into restaurants (name, elo) values('Moxie''s Grill & Bar', '1000');
insert into restaurants (name, elo) values('Mr. Greek', '1000');
insert into restaurants (name, elo) values('Mr. Sub', '1000');
insert into restaurants (name, elo) values('New York Fries', '1000');
insert into restaurants (name, elo) values('Orange Julius', '1000');
insert into restaurants (name, elo) values('Pickle Barrel', '1000');
insert into restaurants (name, elo) values('Pita Pit', '1000');
insert into restaurants (name, elo) values('Pizza Pizza', '1000');
insert into restaurants (name, elo) values('Popeyes', '1000');
insert into restaurants (name, elo) values('Quiznos', '1000');
insert into restaurants (name, elo) values('Richtree Market', '1000');
insert into restaurants (name, elo) values('Second Cup', '1000');
insert into restaurants (name, elo) values('Shanghai 360', '1000');
insert into restaurants (name, elo) values('Smoke''s Poutinerie', '1000');
insert into restaurants (name, elo) values('Subway', '1000');
insert into restaurants (name, elo) values('Swiss Chalet', '1000');
insert into restaurants (name, elo) values('Taco Bell', '1000');
insert into restaurants (name, elo) values('Ten-Ren', '1000');
insert into restaurants (name, elo) values('ThaÃ¯ Express', '1000');
insert into restaurants (name, elo) values('The Keg', '1000');
insert into restaurants (name, elo) values('The Old Spaghetti Factory', '1000');
insert into restaurants (name, elo) values('The Works', '1000');
insert into restaurants (name, elo) values('Tim Hortons', '1000');
insert into restaurants (name, elo) values('Vanelli''s', '1000');
insert into restaurants (name, elo) values('Wendy''s', '1000');
insert into restaurants (name, elo) values('Wild Wing Restaurants', '1000');
insert into restaurants (name, elo) values('Wimpy''s Diner', '1000');
insert into restaurants (name, elo) values('Yogen FrÃ¼z', '1000');
